language: node_js
node_js:
    - "0.12"
addons:
    postgresql: "9.3"
before_script:
    - psql -c "create database headcount_test" -U postgres
    - psql -c "alter user postgres with password 'password'" -U postgres
    - bower install
    - npm install -g mocha migrate
    - migrate
env: TEST_DATABASE_URL="pg://postgres:postgres@localhost/headcount_test"